import argparse
from lxml import etree
from pathlib import Path
import re

CHAR_FOR_PENDING_HEAD = "_"


def _is_condensed_lg(lg_element):
    """Check if an <lg> uses condensed verse format (has <l> children with segment n attributes)."""
    for child in lg_element:
        tag = child.tag if isinstance(child.tag, str) else etree.QName(child.tag).localname
        if tag == 'l' and child.get('n'):
            return True
    return False


class XMLToPlaintext:
    """
    Converts a TEI-XML file generated by tei_builder.py back to the
    lightly-marked plaintext format.

    Drama mode (split_chaya=True): chāyā texts are collected into
    self.chaya_entries instead of being written inline, for output to a
    separate companion file.
    """
    def __init__(self, line_by_line=False, split_chaya=False):
        self.lines = [""]
        self.at_line_start = True
        self.line_by_line = line_by_line
        self.current_lg_base_n = None
        self.in_condensed_lg = False
        self.pending_indent = False
        self.split_chaya = split_chaya
        self.chaya_entries: list[str] = []
        # tracks whether we are inside a <seg type="prakrit"> to know when
        # a nested <seg type="chāyā"> should be intercepted
        self._in_prakrit_seg = False
        # tracks whether the current sp has already emitted "Who — " on the line
        self._sp_header_emitted = False

    def convert(self, xml_path: Path) -> str:
        if not xml_path.exists():
            raise FileNotFoundError(f"Input file not found: {xml_path}")
        try:
            self.tree = etree.parse(str(xml_path))
        except etree.XMLSyntaxError as e:
            raise ValueError(f"Invalid XML in {xml_path}: {e}")

        root = self.tree.getroot()

        body = root.find('{*}text/{*}body')
        if body is None:
            body = root.find('.//{*}body')
        if body is None:
            return ""

        self._process_element(body)

        while self.lines and not self.lines[0]:
            self.lines.pop(0)

        return "\n".join(re.sub(r"\t\s+", "\t", l.rstrip()) for l in self.lines)

    def _append(self, text: str):
        self.lines[-1] += text
        if text.strip():
            self.at_line_start = False

    def _start_new_line(self):
        if self.lines[-1] or not self.at_line_start:
            self.lines.append("")
            self.at_line_start = True

    def _process_text(self, text: str):
        if self.at_line_start:
            text = text.lstrip()
        if not text:
            return
        if '\n' in text:
            processed_text = ' '.join(text.split())
            if not processed_text:
                return
        else:
            processed_text = text
        self._append(processed_text)

    def _collect_text(self, el: etree._Element) -> str:
        """Collect all text content of an element as a plain string."""
        return "".join(el.itertext()).strip()

    def _process_element(self, el: etree._Element):
        tag = etree.QName(el.tag).localname

        # --- CHĀYĀ INTERCEPT ---
        # When inside a <seg type="prakrit"> and we encounter <seg type="chāyā">,
        # either collect it for the companion file or emit inline.
        if tag == 'seg' and el.get('type') == 'chāyā' and self._in_prakrit_seg:
            if self.split_chaya:
                self.chaya_entries.append(self._collect_text(el))
            else:
                self._append("(")
                if el.text:
                    self._process_text(el.text)
                for child in el:
                    self._process_element(child)
                    if child.tail:
                        self._process_text(child.tail)
                self._append(")")
            return  # do not fall through to normal processing

        # --- SKIP <speaker> — its text is already on the line from <sp> ---
        if tag == 'speaker':
            return

        # --- PRE-CHILDREN PROCESSING ---
        if tag == 'sp':
            self._start_new_line()
            who = el.get('who', '')
            self._append(f"{who} — ")
            self._sp_header_emitted = True
        elif tag == 'stage':
            self._append("((")
        elif tag == 'seg' and el.get('type') == 'prakrit':
            self._in_prakrit_seg = True
            self._append("˹")
        elif tag == 'div':
            self._start_new_line()
            self._append(f"{{{el.get('n')}}}")
            self._start_new_line()
        elif tag == 'p':
            self._start_new_line()
            n = el.get('n')
            if n:
                self._append(f"[{n}]")
            if not self.in_condensed_lg:
                self._start_new_line()
        elif tag == 'lg':
            if el.get('type') == 'chāyā':
                # verse-mode chāyā <lg>: one entry for the whole verse
                if self.split_chaya:
                    lines = []
                    for child in el:
                        if etree.QName(child.tag).localname == 'l':
                            lines.append(self._collect_text(child))
                    self.chaya_entries.append("\n".join(lines))
                else:
                    # inline: \t(verse line) for each <l>
                    for child in el:
                        if etree.QName(child.tag).localname == 'l':
                            self._start_new_line()
                            self._append("\t(")
                            self._process_text(self._collect_text(child))
                            self._append(")")
                return  # handled above; skip normal recursion
            parent_tag = etree.QName(el.getparent().tag).localname
            if parent_tag in ('div', 'body', 'sp') or el.get('type') == 'group':
                self._start_new_line()
                if not _is_condensed_lg(el):
                    self._append(f"[{el.get('n')}]")
                self._start_new_line()
        elif tag == 'l':
            if self.in_condensed_lg:
                full_label = (self.current_lg_base_n or '') + (el.get('n') or '')
                self._append(f"[{full_label}]\t")
            else:
                self._append("\t")
        elif tag == 'pb':
            if not self.in_condensed_lg or el.tail is None:
                self._start_new_line()
            if el.get('break') == 'no' and len(self.lines) > 1:
                self.lines[-2] = self.lines[-2].rstrip() + '-'
            if self.in_condensed_lg and el.tail is not None:
                self._append(f" <{el.get('n')}> ")
            else:
                self._append(f"<{el.get('n')}>")
                self._start_new_line()
        elif tag == 'lb':
            if self.line_by_line:
                if el.get('break') == 'no':
                    self.lines[-1] = self.lines[-1].rstrip() + '-'
                self._start_new_line()
            else:
                self._append(" ")
        elif tag == 'milestone':
            self._start_new_line()
            self._append(el.get('n'))
            self._start_new_line()
        elif tag == 'note':
            self._append("(")
        elif tag == 'caesura':
            self.pending_indent = True
        elif tag == 'choice':
            pass  # container
        elif tag == 'sic':
            self._append("≤")
        elif tag == 'corr':
            self._append("«")
        elif tag == 'del':
            self._append("≤")
        elif tag == 'supplied':
            self._append("«")
        elif tag == 'unclear':
            self._append("¿")

        # --- RECURSION ---
        old_lg_base = self.current_lg_base_n
        old_in_condensed = self.in_condensed_lg
        if tag == 'lg':
            self.current_lg_base_n = el.get('n')
            self.in_condensed_lg = _is_condensed_lg(el)

        if el.text:
            self._process_text(el.text)

        for child in el:
            self._process_element(child)

            if child.tail:
                if self.pending_indent:
                    self._append("\t")
                    self.pending_indent = False
                self._process_text(child.tail)

        if tag == 'lg':
            self.current_lg_base_n = old_lg_base
            self.in_condensed_lg = old_in_condensed

        # --- POST-CHILDREN PROCESSING ---
        if tag == 'sp':
            self._start_new_line()
            self._sp_header_emitted = False
        elif tag == 'stage':
            self._append("))")
        elif tag == 'seg' and el.get('type') == 'prakrit':
            self._append("˼")
            self._in_prakrit_seg = False
        elif tag == 'p':
            self._start_new_line()
        elif tag == 'l':
            next_el = el.getnext()
            if next_el is not None and etree.QName(next_el.tag).localname == 'back':
                pass
            else:
                self._start_new_line()
        elif tag == 'back':
            self._start_new_line()
        elif tag == 'head':
            has_lb_child = any(child.tag.endswith('lb') for child in el)
            if has_lb_child:
                self.lines.pop()
                self.lines[-1] += CHAR_FOR_PENDING_HEAD
                self._start_new_line()
            self._append('\t')
        elif tag == 'note':
            self._append(")")
        elif tag == 'sic':
            self._append("≥")
        elif tag == 'corr':
            self._append("»")
        elif tag == 'del':
            self._append("≥")
        elif tag == 'supplied':
            self._append("»")
        elif tag == 'unclear':
            self._append("¿")

    def postprocess(self, plaintext, has_condensed_verses, extra_space_after_location):
        plaintext = plaintext.replace('{', '\n{')

        if not has_condensed_verses:
            plaintext = plaintext.replace('}', '}\n')
            plaintext = re.sub(r'(<[^>]+>)\n+([<\[])', '\n\\1\n\n\\2', plaintext)
            plaintext = plaintext.replace(r'[', '\n[')

        if extra_space_after_location:
            plaintext = plaintext.replace(']', ']\n')

        plaintext = re.sub(r'\n{3,}', '\n\n', plaintext)
        plaintext = re.sub(r'\A\n{1,}', '', plaintext)
        plaintext = re.sub(r'\n{1,}\Z', '\n', plaintext)

        return plaintext


def _detect_has_condensed_verses(xml_path: Path) -> bool:
    tree = etree.parse(str(xml_path))
    for lg in tree.iter('{*}lg'):
        if _is_condensed_lg(lg):
            return True
    return False


def configure_cli(parser: argparse.ArgumentParser):
    parser.description = "Convert TEI-XML back into lightly-marked plaintext."
    parser.add_argument("src", type=Path, help="Source TEI-XML file")
    parser.add_argument("out", type=Path, help="Destination plaintext file")
    parser.add_argument("--line-by-line", action="store_true", help="Enable line-by-line newline logic.")
    parser.add_argument("--extra-space-after-location", action="store_true", help="Add extra blank line after location markers.")
    parser.add_argument("--drama", action="store_true",
                        help="Drama mode: handle speakers and stage directions.")
    parser.add_argument("--chaya", action="store_true",
                        help="Split chāyā into a companion chaya/<stem>.txt file.")


def cli():
    parser = argparse.ArgumentParser()
    configure_cli(parser)
    args = parser.parse_args()

    try:
        converter = XMLToPlaintext(line_by_line=args.line_by_line, split_chaya=args.chaya)
        plaintext = converter.convert(args.src)
        has_condensed = _detect_has_condensed_verses(args.src)
        plaintext = converter.postprocess(plaintext, has_condensed, args.extra_space_after_location)
        args.out.write_text(plaintext, encoding='utf-8')
        print(f"Wrote {args.out}")
        if args.chaya and converter.chaya_entries:
            chaya_out = args.out.parent / 'chaya' / args.out.name
            chaya_out.parent.mkdir(exist_ok=True)
            chaya_out.write_text("\n\n".join(converter.chaya_entries) + "\n", encoding='utf-8')
            print(f"Wrote {chaya_out}")
    except (FileNotFoundError, ValueError) as e:
        print(f"Error: {e}")


if __name__ == "__main__":
    cli()
